name: Build Android Kernel with ZyC Clang

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout kernel source
      uses: actions/checkout@v3

    - name: 🛠️ Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev ccache python3

    - name: 📦 Download and extract ZyC Clang 11.1.0
      run: |

        wget https://github.com/ZyCromerZ/Clang/releases/download/11.1.0-20220724-release/Clang-11.1.0-20220724.tar.gz
        7z x Clang-11.1.0-20220724.tar.gz
        7z x Clang-11.1.0-20220724.tar
       
    - name: 🔧 Set environment variables
      run: |
        echo "KERNEL_DIR=$GITkernel-imageE" >> $GITHUB_ENV
        echo "CLANG_PATH=$GITHUB_WORKSPACE/toolchains/clang" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV

    - name: 🔨 Build kernel
      run: |
        export PATH=$GITHUB_WORKSPACE/Clang-11.1.0-20220724/bin:$PATH
        ls $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/Clang-11.1.0-20220724
        make O=out ARCH=arm64 rosemary_defconfig
        make -j$(nproc) O=out ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=${CROSS_COMPILE} \
            CROSS_COMPILE_ARM32=${CROSS_COMPILE_ARM32} \
            CC=clang \
            LD=ld.lld \
            NM=llvm-nm \
            AR=llvm-ar \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump

    - name: 📁 Upload zImage/Image.gz (tùy kernel)
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: |
          out/arch/arm64/boot/Image.gz-dtb 
